M48
; DRILL file {KiCad (6.0.0-0)} date Thursday, February 03, 2022 at 04:23:41 PM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-02-03T16:23:41-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0-0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.5268Y-5.3748
X3.53Y-2.5
X7.7354Y-5.3724
X7.7366Y-2.4996
T0
M30
